experiencein/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('perfis.urls')),
    path('', include('usuarios.urls'))
]

perfis/urls.py
from django.urls import path
from perfis import views

urlpatterns = [
    path('', views.index, name='index'),
    path('perfis/<int:perfil_id>', views.exibir, name='exibir'),
    path('perfis/<int:perfil_id>/convidar', views.convidar, name='convidar'),
    path('convite/<int:convite_id>/aceitar', views.aceitar, name='aceitar')
] 

usuarios/urls.py
import django
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from usuarios.views import RegistrarUsuarioView

urlpatterns = [
    path('registrar/', RegistrarUsuarioView.as_view(),  name='registrar'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

perfis/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.
class Perfil(models.Model):  
    nome = models.CharField(max_length=255, null=False) 
    email = models.CharField(max_length=255, null=False)
    telefone = models.CharField(max_length=15, null=False)
    nome_empresa = models.CharField(max_length=255, null=False)

    contatos = models.ManyToManyField('self')

    usuario = models.OneToOneField(User,on_delete=models.CASCADE, related_name='perfil')

    @property
    def email(self):
        return self.usuario.email

    def convidar(self, perfil_convidado):
        Convite(solicitante=self, convidado=perfil_convidado).save()
          
class Convite(models.Model):
    solicitante = models.ForeignKey(Perfil, on_delete=models.CASCADE, related_name='convites_feitos')    
    convidado = models.ForeignKey(Perfil,on_delete=models.CASCADE, related_name='convites_recebidos')

    def aceitar(self):
        self.convidado.contatos.add(self.solicitante)
        self.convidado.contatos.add(self.convidado)
        self.delete()

usuarios/models.py
from django.db import models

# Create your models here.

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User


class RegistrarUsuarioForm(forms.Form):
    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    nome_empresa = forms.CharField(required=True)  


    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Por favor, verifique os dados')
            valid = False

        user_exists = User.objects.filter(username=self.data['nome']).exists()

        if user_exists:
            self.adiciona_erro('Usuário já existente')
            valid = False
            
        return valid


    def adiciona_erro(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)

perfis/views.py
from django.shortcuts import redirect, render
from perfis.models import Convite, Perfil
from django.contrib.auth.decorators import login_required, permission_required
# Create your views here.

@login_required
def index(request):
    print(request.user.username) #novo
    print(request.user.email) #novo
    print(request.user.has_perm('perfis.redirect')) #novo

    return render(
        request,'index.html',
        {
        'perfis': Perfil.objects.exclude(nome=request.user.perfil.nome), 
        'perfil_logado' : get_perfil_logado(request)
        })

@login_required
def exibir(request, perfil_id):
    perfil = Perfil.objects.get(id=perfil_id)
    perfil_logado = get_perfil_logado(request)
    ja_e_contato = perfil in perfil_logado.contatos.all()
    return render(request,'perfil.html',{'perfil':perfil,'perfil_logado':perfil_logado,'ja_e_contato':ja_e_contato})

@permission_required('perfis.add_convite',raise_exception=True)
@login_required
def convidar(request, perfil_id):
    perfil_a_convidar = Perfil.objects.get(id=perfil_id)
    perfil_logado = get_perfil_logado(request)
    perfil_logado.convidar(perfil_a_convidar)
    return redirect('index')

@login_required
def get_perfil_logado(request):   
    return request.user.perfil

@login_required
def aceitar(request,convite_id):
    convite = Convite.objects.get(id=convite_id) 
    convite.aceitar()  
    return redirect('index')


      

      

usuarios/views.py
from django.shortcuts import redirect, render
from django.views.generic.base import View
from django.contrib.auth.models import User
from perfis.models import Perfil
from usuarios.forms import RegistrarUsuarioForm
# Create your views here.
class RegistrarUsuarioView(View):
    template_name = 'registrar.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):

        #preenche o from
        form = RegistrarUsuarioForm(request.POST)

         #verifica se eh valido
        if form.is_valid():
            dados_form = form.data

            usuario = User.objects.create_user(dados_form['nome'], dados_form['email'], dados_form['senha'])

            #cria o perfil
            perfil = Perfil.objects.create(
                    nome=dados_form['nome'],
                    telefone=dados_form['telefone'],
                    nome_empresa=dados_form['nome_empresa'],
                    usuario=usuario
                )

            #grava no banco
            perfil.save()

            #redireciona para a index
            return redirect('index')

        #so chega aqui se nao for valido
        #vamos devolver o form para mostrar o formulario preenchido         
        return render(request, self.template_name, { 'form': form })

perfis/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    <title>ExperienceIn</title>
</head>

<body>
    <div class="container">
        <!-- <div class="header">
            <ul class="nav nav-pills pull-right">
                <li class=""><a href="{% url 'index' %}">{{perfil_logado.nome}}</a></li>
                <li class=""><a href="/logout/">Logout</a></li>
            </ul>
            <h3 class="text-muted">ExperienceIn</h3>
        </div> -->

        {% include "navbar.html" %}

        <div class="row content">
            <!-- conteúdo da página entraria aqui -->
            {% block body %}
            {% endblock %}
        </div>
    </div>
</body>

</html>

perfis/templates/index.html
{% extends "base.html" %}

{% block body %}
<div class="col-lg-12">
    <strong>Todos os Perfis</strong>
    {% with total_de_contatos=perfil.contatos.count %}
    {% if perfis %}
    <ul class="list-group">
        {% for perfil in perfis %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <a class="list-group-item " href="{% url 'exibir' perfil.id %}">
                {{perfil.nome.upper}} </a>
            <span class="badge bg-primary rounded-pill">
                {{ perfil.contatos.count }}
                Contatos
            </span>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Nenhum Perfil encontrado</p>
    {% endif %}
    {% endwith %}
</div>
<!-- bloco novo de código que exibe os convites -->

<div class="panel panel-info my-5">
    {% with total_de_convites=perfil_logado.convites_recebidos.count %}
    {% if perfil_logado.convites_recebidos.count %}
    <div class="panel-heading">
        <strong>
            Você tem {{ total_de_convites }} convite{{total_de_convites|pluralize}} aguardando
            aprovação
        </strong>
    </div>
    <ul class="list-group">
        {% for convite in perfil_logado.convites_recebidos.all %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            {{ convite.solicitante.nome }}
            <a class='btn btn-outline-success' href="{% url 'aceitar' convite.id %}" class="pull-right">aceitar</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}

    <p class="text-secondary my-5 border border-primary">Nenhum solicitação encontrada :( </p>

    {% endif %}
    {% endwith %}
</div>

<!-- fim do bloco novo -->

<!-- novo painel! -->

<div class="panel panel-info">
    {% with total_de_contatos=perfil_logado.contatos.count %}
    {% if total_de_contatos %}

    <strong>Você tem {{total_de_contatos}} contato{{ total_de_contatos|pluralize }}</strong>

    <ul class="list-group">
        {% for contato in perfil_logado.contatos.all %}
        <li class="list-group-item">
            <a href="{% url 'exibir' contato.id %}">{{ contato.nome }}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}

    <p>Você não possui contatos no momento :(</p>

    {% endif %}
    {% endwith %}
</div>
<!-- fim do novo painel! -->


{% endblock %}

perfis/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">ExperienceIn</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03"
            aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor03">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'index' %}">
                        {{perfil_logado.nome}}
                        <span class="visually-hidden">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/logout/">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

perfis/templates/perfil.html
<!-- experiencein/perfis/template/perfil.html -->

{% extends "base.html" %}

{% block body %}
<!-- <div class="row">
    <div class="col-lg-12">
        <h2 style="margin-top:0">{{perfil.nome}}</h2>
        <address>
          <strong>{{perfil.nome_empresa}}</strong><br>
          <abbr title="Telefone">Tel:</abbr> {{perfil.telefone}}<br>
          <a href="mailto:{{perfil.email}}">{{perfil.email}}</a>
        </address>
        {% if ja_e_contato %}
          <div class="well well-sm">Vocês estão conectados!</div>
        {% else %}
          <a href="{% url 'convidar' perfil.id %}">convidar</a>
        {% endif %}  
    </div>
</div> -->
<div class="card text-white bg-dark mb-3" style="max-width: 20rem;">
  <!-- <div class="card-header">{{perfil.nome}}</div> -->
  <div class="card-body">
    <h4 class="card-title">{{perfil.nome}}</h4>
    <p class="card-text">
    <address>
      <strong>{{perfil.nome_empresa}}</strong><br>
      <abbr title="Telefone">Tel: {{perfil.telefone}}</abbr><br>
      <a href="mailto:{{perfil.email}}">{{perfil.email}}</a>
    </address>
    {% if ja_e_contato %}
    <div class="well well-sm">Vocês estão conectados!</div>
    {% else %}
    <a class="btn btn-outline-success" href="{% url 'convidar' perfil.id %}">
      convidar
    </a>
    {% endif %}
    </p>
  </div>
</div>
{% endblock %}

usuarios/templates/base_usuario.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'styles/signin.css' %}">
    <title>ExperienceIn</title>
</head>

<body>
    <div class="container">
        {% block body %}

        {% endblock %}
    </div>
</body>

</html>

usuarios/templates/login.html
{% extends "base_usuario.html" %}

{% block body %}

<form class="form-signin" role="form" action="{% url 'login' %}" method="post">
    {% csrf_token %}
    <h2 class="form-signin-heading">Login</h2>

    <input type="text" id="id_username" name="username" class="form-control mt-4" placeholder="Nome" required autofocus>

    <input type="password" id="id_password" name="password" class="form-control mt-4" placeholder="Senha" required>

    <button class="btn btn-lg btn-primary btn-block mt-4" type="submit" value="Login">Login</button>

    <input type="hidden" name="next" value="{{ next }}" />

    {% if form.errors %}
    <div class="alert alert-danger mt-4">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        Por favor, verifique o Email e/ou Senha informados
    </div>
    {% endif %}

    <a class="btn" href="{% url 'registrar' %}">registre-se</a>
</form>

{% endblock %}

usuarios/templates/registrar.html
{% extends "base_usuario.html" %}

{% block body %}
<form class="form-signin" action="{% url 'registrar' %}" method="post">

    {% csrf_token %}

    <h2 class="form-signin-heading">Crie seu usuário</h2>

    <input type="text" id="id_email" name="email" class="form-control mt-4" placeholder="Email *" required autofocus>

    <input type="text" id="id_nome" name="nome" class="form-control mt-2" placeholder="Nome *" required>

    <input type="password" id="id_senha" name="senha" class="form-control mt-2" placeholder="Senha *" required>

    <hr />

    <input type="tel" id="id_telefone" name="telefone" class="form-control mt-2" placeholder="Telefone">

    <input type="text" id="id_nome_empresa" name="nome_empresa" class="form-control mt-2" placeholder="Empresa">

    <hr />

    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button>

    {% if form.errors %}
    <div class="alert alert-danger">
        <span>Erro ao registrar usuário: </span>
        <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;</button>
    </div>
    {% endif %}

</form>
{% endblock %}